name: Automated release
description: "Action used for automated releases bumping version based on commit message"

outputs:
  version:
    description: Rleased version
    value: ${{ steps.release.outputs.tag_name }}

runs:
  using: "composite"
  steps:
      - name: Check head commit message
        id: commit_msg
        shell: bash
        run: |
          cat > /tmp/commit-msg.txt  <<ENDcommitMSG
          ${{ github.event.head_commit.message }}
          ENDcommitMSG

          RELEASE_TYPE=$(cat /tmp/commit-msg.txt | grep -Po "\[(minor|major|patch)\]" || true) 
          [ ${RELEASE_TYPE} ] && RELEASE_TYPE=$(echo ${RELEASE_TYPE} | grep -Po "(minor|major|patch)")
          echo "::set-output name=release_type::${RELEASE_TYPE}"

      - name: Release
        id: release
        if: ${{ steps.commit_msg.outputs.release_type }}
        uses: rymndhng/release-on-push-action@master
        with:
          tag_prefix: v
          bump_version_scheme: ${{ steps.commit_msg.outputs.release_type }}
          release_name: "Release <RELEASE_VERSION>"

      - name: Test
        shell: bash 
        run: |
          echo ${{ steps.release.outputs.tag_name }}
